name: Publish GHCR images

on:
  push:
    branches:
      - main

permissions: {}

jobs:
  publish:
    permissions:
      contents: read
      packages: write
    runs-on: ubuntu-latest
    steps:
      - name: Clone the code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: Log in to GHCR
        uses: docker/login-action@184bdaa0721073962dff0199f1fb9940f07167d1 # v3.5.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@29109295f81e9208d7d86ff1c6c12d2833863392 # v3.6.0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@8d2750c68a42422c14e847fe6c8ac0403b4cbd6f # v3.12.0

      - name: Set image tags
        id: meta
        run: |
          short_sha="${GITHUB_SHA::7}"
          {
            echo "short_sha=${short_sha}"
            echo "image=ghcr.io/grafana/k8s-injection-controller"
            echo "tags<<EOF"
            echo "ghcr.io/grafana/k8s-injection-controller:main"
            echo "ghcr.io/grafana/k8s-injection-controller:${short_sha}"
            echo "EOF"
          } >> "$GITHUB_OUTPUT"

      - name: Build and push image
        uses: docker/build-push-action@263435318d21b8e681c14492fe198d362a7d2c83 # v6.18.0
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ${{ steps.meta.outputs.image }}:main
            ${{ steps.meta.outputs.image }}:${{ steps.meta.outputs.short_sha }}
